### PR TITLE
Graph

### PR DESCRIPTION
**Pull request by vritant24**
Graph now communicates with back-end
GeoJSON layer looks better

### CODE REVIEW

**Comment by drewatk** [comment]
Sorry this is super late. I was saying that we should just delete app.js and the import statement altogether
Is there a reason it needs to still be there?

**Comment by vritant24** [comment]
It doesn't have to be there, I just thought that there is a chance it could be used later on. I can just delete it. It makes no difference

**Comment by drewatk** [comment]
We'll just add it back if we need it I guess. No point in having random commented code

**Comment by vritant24** [comment]
Deleted

**Pull request merged**
